### ISSUE TITLE
视频链接带空格时导致出错

### ISSUE THREAD

**Issue by ChengChung** [RoyaAoki/Megumin#2]
能够复现此情况的视频比如：3lion、徒然children等，发现当解析出来的链接带空格时无法正常播放。

>08-20 13:59:23.179 1032-1032/com.sqrtf.megumin I/PlayerActivity: playing:https://static.suki.moe/video/252c61c9-afbd-49b7-bbe7-097a060a9ab5/[UHA-WINGS][Tsurezure Children][02][1080p][GB].mp4
08-20 13:59:23.185 1032-1189/com.sqrtf.megumin E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
08-20 13:59:23.185 1032-1189/com.sqrtf.megumin D/AppTracker: App Event: start
08-20 13:59:23.205 1032-1188/com.sqrtf.megumin D/OpenGLRenderer: endAllStagingAnimators on 0x7fa570d400 (CardView) with handle 0x7f99c7e8a0
08-20 13:59:23.935 1032-1463/com.sqrtf.megumin D/skia: --- SkImageDecoder::Factory returned null
08-20 13:59:23.936 1032-1463/com.sqrtf.megumin D/skia: --- SkImageDecoder::Factory returned null
08-20 13:59:23.941 1032-1461/com.sqrtf.megumin D/skia: --- SkImageDecoder::Factory returned null
08-20 13:59:23.942 1032-1461/com.sqrtf.megumin D/skia: --- SkImageDecoder::Factory returned null
08-20 13:59:23.962 1032-1459/com.sqrtf.megumin D/skia: --- SkImageDecoder::Factory returned null
08-20 13:59:23.965 1032-1459/com.sqrtf.megumin D/skia: --- SkImageDecoder::Factory returned null 
08-20 13:54:29.200 1032-1479/com.sqrtf.megumin E/ExoPlayerImplInternal: Source error.
                                                                        com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                            at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                            at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)

另如果可能想请求一个功能：在登录界面上增加忽略https相关验证的选项，并适用于APIClient和视频流的连接，因为在Android4.4下，连接suki.moe时会提示unknown error，具体原因是SSL握手时失败。猜测可能是服务器上挂的LE证书不是fullchain？

**Comment by RoyaAoki** [comment]
链接带空格的问题不能重现，不能播放应该和空格无关。需要再确认下设备或网络情况？

**Comment by ChengChung** [comment]
网络应该没有问题，设备是TV(4.4)、手机(6.0)
我拿当前的源码重新编译了一遍，依然能重现，有些日剧也一样不能播放
操作视频：https://drive.google.com/open?id=0B15pJSgjB5oYLWhfYUFOZllNWDg
对应日志：https://paste.ubuntu.com/25363164/
之前在fixHttpUrl里把空格替换成%20能解决一部分播放问题，所以我觉得不是网络问题
将url中把文件名用Uri.encode之后上述提到的日剧也能播放。

**Comment by RoyaAoki** [comment]
在6.0模拟器上跑了下确实是空格问题 [这里](https://github.com/google/ExoPlayer/issues/871) 也提到了..
替换成%20应该没问题

**Comment by RoyaAoki** [comment]
3lion 17话在模拟器会出现storeMetaDataInBuffers failed w/ err -1010.. 在真实设备(oneplus 3t)上却可以正常播放
对于这类解码方面的问题暂时考虑加个用外部播放器打开的功能？

**Comment by ChengChung** [comment]
在3t上（android6.0）播放是色彩异常，大概就这个效果：http://i.imgur.com/pQIOEUG.png
用外部播放器打开应该可行

存在问题的应该还包括非英文url

**Comment by Laeoo** [comment]
这个怎么用啊
